<?php
    $collection = $this->getCollection();
    $phones = Mage::helper('sp_events')->getHeaderPhones();
?>

<?php if (Mage::helper('sp_events')->isEnabled() &&  Mage::helper('sp_events')->getDateRange()): ?>
    <div class="events-wrapper">
        <h1><?php echo $this->__('Events') ?></h1>
        <div class="events">
            <?php foreach ($collection as $item): ?>
                Mage::getBaseUrl('media', );
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>