<?php

/**
 * @author Pavel Usachev <webcodekeeper@hotmail.com>
 * @copyright Copyright (c) 2017, Pavel Usachev
 */

require_once(Mage::getModuleDir('controllers','Mage_Contacts').DS.'IndexController.php');

class SP_FeaturedLinks_IndexController
    extends Mage_Contacts_IndexController
{
    public function postAction()
    {
        return parent::postAction(); // TODO: Change the autogenerated stub
    }
}